### ISSUE TITLE
Error with django 1.8 and wiki from master

### ISSUE THREAD

**Issue by artainis** [django-wiki/django-wiki#424]
django-wiki: needs django.core.context_processors.request in TEMPLATE_CONTEXT_PROCESSORS')
django.core.exceptions.ImproperlyConfigured: django-wiki: needs django.core.context_processors.request in TEMPLATE_CONTEXT_PROCESSORS

It seems django.core.context_processors has been depreciated in 1.8 into django.template.context_processors.

**Comment by benjaoming** [comment]
thanks for reporting!

true that, would you be able to provide a backwards compatible fix?

**Comment by artainis** [comment]
I'm still new to Django and programming in general. Do I have to do something like an "if django version 1.8 then xxxx." for everyplace in the app where those modules appear?

How did you guys get it to work with 1.8 before?

**Comment by artainis** [comment]
modifying the wiki/models/__init__.py line 51 like this gets rid of the improperly configured error. Have to put the new location of the context processors in the settings and change from 'core' to 'templates':

if not 'django.template.context_processors.request' in django_settings.TEMPLATES[0]['OPTIONS']['context_processors']:
    raise ImproperlyConfigured(
        'django-wiki: needs django.template.context_processors.request in TEMPLATE_CONTEXT_PROCESSORS')

**Comment by artainis** [comment]
I believe a backwards compatible fix would be like this?:

import django

if django.VERSION == (1, 8, 1, 'final', 0):
	if not 'django.template.context_processors.request' in django_settings.TEMPLATES[0]['OPTIONS']['context_processors']:
	    raise ImproperlyConfigured(
	        'django-wiki: needs django.template.context_processors.request in TEMPLATE_CONTEXT_PROCESSORS')

else:
	if not 'django.core.context_processors.request' in django_settings.TEMPLATES_CONTEXT_PROCESSORS:
	    raise ImproperlyConfigured(
	        'django-wiki: needs django.core.context_processors.request in TEMPLATE_CONTEXT_PROCESSORS')

**Comment by benjaoming** [comment]
You can do `django.VERSION < (1, 8)`.

**Comment by artainis** [comment]
I see. Can I become a contributor to this project?

**Comment by benjaoming** [comment]
@artainis it's not complicated, just do a PR, I'll have a look :)

**Comment by benjaoming** [comment]
:+1:

**Comment by artainis** [comment]
Ah. So I should fork it into my personal repository, make changes, and then make a pull request to have changes that are good merged into the master? And then to keep my version up to date but also keep my changes that haven't been accepted into the upstream/master, I should do a rebase (rather than a merge)?

**Comment by benjaoming** [comment]
Standard practice ;) Make a clone, make a branch, make changes, submit a PR for your own branch. Later, you can pull changes from upstream into your own clone's master.

Rebase is when you want changes from upstream and not to merge your own stuff, but rather alter your own commits to replay on top of newer commits.

Git is not simple, I cannot explain it :)

**Comment by artainis** [comment]
![image](https://cloud.githubusercontent.com/assets/12302696/7595623/b82ec49a-f8ad-11e4-873c-63485a5b8ef3.png)

Is the default supposed to look like this?

**Comment by benjaoming** [comment]
@artainis please do not use Github issues for support questions.. no of course it's not supposed to look like that, you can refer to the demo site: http://demo.django-wiki.org/

**Comment by benjaoming** [comment]
Since this was fixed in #427, I'm closing this issue :)

**Comment by emorozov** [comment]
I think this doesn't work still. Shouldn't this line:
```
if not 'django.contrib.auth.context_processors.auth' in django_settings.TEMPLATE_CONTEXT_PROCESSORS:
```
be:
```
if not 'django.contrib.auth.context_processors.auth' in TEMPLATE_CONTEXT_PROCESSORS:
```

I still get the error on Django 1.9.9

**Comment by benjaoming** [comment]
Yeah, wondering how this obvious mistake sneaked into the PR since this was what it was supposed to have fixed :)

I guess it's because our tests are running with an old settings layout and thus the error isn't picked up...

**Comment by benjaoming** [comment]
It's been fixed properly now. I'm waiting to see how Django 1.10 works out before making the next release.

**Comment by benjaoming** [comment]
This is released starting from 0.2b1
